In [2]:
import OpenDartReader

In [3]:
api_key = '7e4400d321b22388767c3eded0823102081c97d9'

dart = OpenDartReader(api_key)

In [136]:
dart.finstate_all('삼성카드', 2018)

In [147]:
val_list = dart.list('029780')
val_list

,corp_code,corp_name,stock_code,corp_cls,report_nm,rcept_no,flr_nm,rcept_dt,rm
0,00126292,삼성카드,029780,Y,풍문또는보도에대한해명(미확정),20211216800649,삼성카드,20211216,유
1,00126292,삼성카드,029780,Y,임원ㆍ주요주주특정증권등소유상황보고서,20211210000700,삼성생명,20211210,
2,00126292,삼성카드,029780,Y,최대주주등소유주식변동신고서,20211206800205,삼성카드,20211206,유
3,00126292,삼성카드,029780,Y,임원ㆍ주요주주특정증권등소유상황보고서,20211203000005,삼성생명,20211203,
4,00126292,삼성카드,029780,Y,특수관계인과의리스거래,20211201000050,삼성카드,20211201,공
...,...,...,...,...,...,...,...,...,...
96,00126292,삼성카드,029780,Y,유가증권-수익증권,20000710000170,삼성카드,20000710,공
97,00126292,삼성카드,029780,Y,유가증권-수익증권,20000710000162,삼성카드,20000710,공
98,00126292,삼성카드,029780,Y,장단기차입,20000710000149,삼성카드,20000710,공
99,00126292,삼성카드,029780,Y,보험,20000710000098,삼성카드,20000710,공
0,00126292,삼성카드,029780,Y,감사보고서 (1999.12),20000404000075,안진회계법인,20000404,

In [146]:
val_list

0        풍문또는보도에대한해명(미확정)
1     임원ㆍ주요주주특정증권등소유상황보고서
2          최대주주등소유주식변동신고서
3     임원ㆍ주요주주특정증권등소유상황보고서
4             특수관계인과의리스거래
             ...
96              유가증권-수익증권
97              유가증권-수익증권
98                  장단기차입
99                     보험
0         감사보고서 (1999.12)
Name: report_nm, Length: 5301, dtype: object

In [148]:
for i in val_list['report_nm'].values:
    if '사업보고서' in i:
        print(i)
        
'연결재무제표기준영업(잠정)실적(공정공시)'

사업보고서 (2020.12)
사업보고서 (2019.12)
사업보고서 (2018.12)
사업보고서 (2017.12)
사업보고서 (2016.12)
사업보고서 (2015.12)
사업보고서 (2014.12)
사업보고서 (2013.12)
사업보고서 (2012.12)
[첨부추가]사업보고서 (2011.12)
[첨부추가]사업보고서 (2010.12)
[첨부추가]사업보고서 (2009.12)
[첨부추가]사업보고서 (2008.12)
[첨부추가]사업보고서 (2007.12)
[첨부추가]사업보고서 (2006.12)
[기재정정]사업보고서 (2005.12)
[기재정정]사업보고서 (2004.12)
[첨부추가]사업보고서 (2003.12)
[첨부추가]사업보고서 (2002.12)
[첨부추가]사업보고서 (2001.12)
[첨부추가]사업보고서 (2000.12)

'연결재무제표기준영업(잠정)실적(공정공시)'

In [8]:
# 삼성전자 2018년 사업보고서
attaches = dart.attach_file_list('20190401004781')
attaches

,file_name,url,type
0,[삼성전자]사업보고서(2019.04.01).pdf,http://dart.fss.or.kr/pdf/download/pdf.do?rcp_...,pdf
1,[삼성전자]사업보고서_재무제표(2019.04.01)_ko.xls,http://dart.fss.or.kr/pdf/download/excel.do?rc...,excel
2,[삼성전자]사업보고서_IFRS(원문XBRL)(2019.04.01).zip,http://dart.fss.or.kr/pdf/download/ifrs.do?rcp...,ifrs

In [9]:
xls_url = attaches.loc[attaches['type']=='excel', 'url'].values[0] # 첨부 재무제표 엑셀
xls_url

'http://dart.fss.or.kr/pdf/download/excel.do?rcp_no=20190401004781&dcm_no=6616741&lang=ko'

In [10]:
dart.retrieve(xls_url, '삼성전자_2018.xls')

'삼성전자_2018.xls'

In [11]:
import pandas as pd

xl = pd.ExcelFile('삼성전자_2018.xls')
xl.sheet_names

['기본정보',
 '연결 재무상태표',
 '연결 손익계산서',
 '연결 포괄손익계산서',
 '연결 자본변동표',
 '연결 현금흐름표',
 '재무상태표',
 '손익계산서',
 '포괄손익계산서',
 '자본변동표',
 '현금흐름표']

In [12]:
pd.read_excel('삼성전자_2018.xls', sheet_name='연결 손익계산서', skiprows=6)

                                       제 50 기     제 49 기     제 48 기
0                          수익(매출액)  243771415  239575376  201866745
1                             매출원가  132394411  129290661  120277715
2                            매출총이익  111377004  110284715   81589030
3                          판매비와관리비   52490335   56639677   52348358
4                         영업이익(손실)   58886669   53645038   29240672
5                             기타수익    1485037    3010657    3238261
6                             기타비용    1142018    1419648    2463814
7                            지분법이익     539845     201442      19501
8                             금융수익    9999321    9737391   11385645
9                             금융비용    8608896    8978913   10706613
10                 법인세비용차감전순이익(손실)   61159958   56195967   30713652
11                           법인세비용   16815101   14009220    7987560
12                      계속영업이익(손실)   44344857   42186747   22726092
13                       당기순이익(손실)   44344857   42186747   22726092
14                   당기순이익(손실)의 귀속
15      지배기업의 소유주에게 귀속되는 당기순이익(손실)   43890877   41344569   22415655
16           비지배지분에 귀속되는 당기순이익(손실)     453980     842178     310437
17                            주당이익
18             기본주당이익(손실) (단위 : 원)       6461       5997       3159
19             희석주당이익(손실) (단위 : 원)       6461       5997       3159

In [151]:
df = dart.major_shareholders_exec('삼성카드')
df

,rcept_no,rcept_dt,corp_code,corp_name,repror,isu_exctv_rgist_at,isu_exctv_ofcps,isu_main_shrholdr,sp_stock_lmp_cnt,sp_stock_lmp_irds_cnt,sp_stock_lmp_rate,sp_stock_lmp_irds_rate
0,20191223000050,2019-12-23,00126292,삼성카드,삼성생명,-,-,10%이상주주,"83,285,486",854,71.89,0.01
1,20191231000148,2019-12-31,00126292,삼성카드,삼성생명,-,-,10%이상주주,"83,288,247","2,761",71.89,0.00
2,20200103000544,2020-01-03,00126292,삼성카드,삼성생명,-,-,10%이상주주,"83,288,185",-62,71.89,0.00
3,20200113000003,2020-01-13,00126292,삼성카드,삼성생명,-,-,10%이상주주,"83,288,128",-57,71.89,0.00
4,20200117000422,2020-01-17,00126292,삼성카드,삼성생명,-,-,10%이상주주,"83,288,195",67,71.89,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...
101,20211115000040,2021-11-15,00126292,삼성카드,삼성생명,-,-,10%이상주주,"83,332,596","3,567",71.93,0.01
102,20211119000529,2021-11-19,00126292,삼성카드,삼성생명,-,-,10%이상주주,"83,331,019","-1,577",71.92,-0.01
103,20211126000557,2021-11-26,00126292,삼성카드,삼성생명,-,-,10%이상주주,"83,331,617",598,71.93,0.01
104,20211203000005,2021-12-03,00126292,삼성카드,삼성생명,-,-,10%이상주주,"83,331,564",-53,71.93,0.00
105,20211210000700,2021-12-10,00126292,삼성카드,삼성생명,-,-,10%이상주주,"83,313,197","-18,367",71.91,-0.02

In [10]:
attaches = dart.attach_file_list('20211215000121')
attaches

,file_name,url,type
0,[삼성전자]임원ㆍ주요주주특정증권등소유상황보고서(2021.12.15).pdf,http://dart.fss.or.kr/pdf/download/pdf.do?rcp_...,pdf

In [14]:
df[df['rcept_no'] == '20190401004781']

Empty DataFrame
Columns: [rcept_no, rcept_dt, corp_code, corp_name, repror, isu_exctv_rgist_at, isu_exctv_ofcps, isu_main_shrholdr, sp_stock_lmp_cnt, sp_stock_lmp_irds_cnt, sp_stock_lmp_rate, sp_stock_lmp_irds_rate]
Index: []

In [77]:
rcp_no = dart.finstate('Kakao', 2018)
rcp_no

TypeError: argument of type 'NoneType' is not iterable

In [25]:
# 삼성전자 2020년 사업보고서
attaches = dart.attach_file_list(rcp_no)
attaches

,file_name,url,type
0,[삼성전자]사업보고서(2021.03.09).pdf,http://dart.fss.or.kr/pdf/download/pdf.do?rcp_...,pdf
1,[삼성전자]사업보고서_재무제표(2021.03.09)_ko.xls,http://dart.fss.or.kr/pdf/download/excel.do?rc...,excel
2,[삼성전자]사업보고서_IFRS(원문XBRL)(2021.03.09).zip,http://dart.fss.or.kr/pdf/download/ifrs.do?rcp...,ifrs

In [42]:
xls_url = attaches.loc[attaches['type']=='excel', 'url'].values[0] # 첨부 재무제표 엑셀
xls_url

'http://dart.fss.or.kr/pdf/download/excel.do?rcp_no=20210309000744&dcm_no=7861003&lang=ko'

In [43]:
import os
import pandas as pd

In [45]:
file_name = '삼성전자_2020.xls'

dart.retrieve(xls_url, file_name)

df = pd.read_excel(file_name, sheet_name='연결 손익계산서', skiprows=6)

os.remove(file_name)

In [75]:
os.remove(file_name)

In [56]:
df[df[' '] == '수익(매출액)']

               제 52 기     제 51 기     제 50 기
0  수익(매출액)  236806988  230400881  243771415

In [ ]:
import os
import pandas as pd

In [170]:
key_word = '097520'

# print(dart.finstate(key_word, 2020))
rcp_no = dart.finstate(key_word, 2020).loc[0, 'rcept_no']
# 삼성전자 2020년 사업보고서
attaches = dart.attach_file_list(rcp_no)
# 첨부 재무제표 엑셀
xls_url = attaches.loc[attaches['type']=='excel', 'url'].values[0]

file_name = f'{key_word}_2020.xls'

dart.retrieve(xls_url, file_name)
df = pd.read_excel(file_name, sheet_name='연결 포괄손익계산서')
os.remove(file_name)

# print(df.head(20))
print(df.iloc[4].values[0])
print('매출액: ', df.iloc[6].values[1])
print('영업이익: ', df.iloc[10].values[1])
print(df[df['Unnamed: 0'].isin(['당기순이익(손실)'])].iloc[0].values[1])
# print('당기순이익: ', df['당기순이익' in df[' ']][0].values[1])

(단위 : 원)
매출액:  1311342738149
영업이익:  59167161589
38443583445

In [157]:
dart.company('029780')

{'status': '000',
 'message': '정상',
 'corp_code': '00126292',
 'corp_name': '삼성카드(주)',
 'corp_name_eng': 'SAMSUNG CARD CO.,LTD',
 'stock_name': '삼성카드',
 'stock_code': '029780',
 'ceo_nm': '김대환',
 'corp_cls': 'Y',
 'jurir_no': '1101110346901',
 'bizr_no': '2028145602',
 'adres': '서울특별시 중구  세종대로 67',
 'hm_url': 'www.samsungcard.co.kr',
 'ir_url': '',
 'phn_no': '02-1588-8700',
 'fax_no': '757-6056',
 'induty_code': '64913',
 'est_dt': '19830324',
 'acc_mt': '12'}