In [3]:
import OpenDartReader

In [4]:
api_key = '7e4400d321b22388767c3eded0823102081c97d9'

dart = OpenDartReader(api_key)

In [7]:
dart.finstate_all('005930', 2018)

,rcept_no,reprt_code,bsns_year,corp_code,sj_div,sj_nm,account_id,account_nm,account_detail,thstrm_nm,thstrm_amount,frmtrm_nm,frmtrm_amount,bfefrmtrm_nm,bfefrmtrm_amount,ord,thstrm_add_amount
0,20190401004781,11011,2018,00126380,BS,재무상태표,ifrs_CurrentAssets,유동자산,-,제 50 기,174697424000000,제 49 기,146982464000000,제 48 기,141429704000000,1,NaN
1,20190401004781,11011,2018,00126380,BS,재무상태표,ifrs_CashAndCashEquivalents,현금및현금성자산,-,제 50 기,30340505000000,제 49 기,30545130000000,제 48 기,32111442000000,2,NaN
2,20190401004781,11011,2018,00126380,BS,재무상태표,dart_ShortTermDepositsNotClassifiedAsCashEquiv...,단기금융상품,-,제 50 기,65893797000000,제 49 기,49447696000000,제 48 기,52432411000000,3,NaN
3,20190401004781,11011,2018,00126380,BS,재무상태표,-표준계정코드 미사용-,단기매도가능금융자산,-,제 50 기,,제 49 기,3191375000000,제 48 기,3638460000000,4,NaN
4,20190401004781,11011,2018,00126380,BS,재무상태표,-표준계정코드 미사용-,단기상각후원가금융자산,-,제 50 기,2703693000000,제 49 기,,제 48 기,,5,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
213,20190401004781,11011,2018,00126380,SCE,자본변동표,ifrs_Equity,기말자본,자본 [member]|지배기업 소유주지분|기타자본항목,제 50 기,-7931370000000,제 49 기,-13899191000000,제 48 기,-11934586000000,19,NaN
214,20190401004781,11011,2018,00126380,SCE,자본변동표,ifrs_Equity,기말자본,자본 [member]|지배기업 소유주지분|매각예정분류기타자본항목,제 50 기,,제 49 기,,제 48 기,-28810000000,19,NaN
215,20190401004781,11011,2018,00126380,SCE,자본변동표,ifrs_Equity,기말자본,자본 [member]|지배기업 소유주지분|이익잉여금 [member],제 50 기,242698956000000,제 49 기,215811200000000,제 48 기,193086317000000,19,NaN
216,20190401004781,11011,2018,00126380,SCE,자본변동표,ifrs_Equity,기말자본,자본 [member]|지배기업 소유주지분|자본금 [member],제 50 기,897514000000,제 49 기,897514000000,제 48 기,897514000000,19,NaN
217,20190401004781,11011,2018,00126380,SCE,자본변동표,ifrs_Equity,기말자본,자본 [member]|지배기업 소유주지분|주식발행초과금,제 50 기,4403893000000,제 49 기,4403893000000,제 48 기,4403893000000,19,NaN

In [8]:
# 삼성전자 2018년 사업보고서
attaches = dart.attach_file_list('20190401004781')
attaches

,file_name,url,type
0,[삼성전자]사업보고서(2019.04.01).pdf,http://dart.fss.or.kr/pdf/download/pdf.do?rcp_...,pdf
1,[삼성전자]사업보고서_재무제표(2019.04.01)_ko.xls,http://dart.fss.or.kr/pdf/download/excel.do?rc...,excel
2,[삼성전자]사업보고서_IFRS(원문XBRL)(2019.04.01).zip,http://dart.fss.or.kr/pdf/download/ifrs.do?rcp...,ifrs

In [9]:
xls_url = attaches.loc[attaches['type']=='excel', 'url'].values[0] # 첨부 재무제표 엑셀
xls_url

'http://dart.fss.or.kr/pdf/download/excel.do?rcp_no=20190401004781&dcm_no=6616741&lang=ko'

In [10]:
dart.retrieve(xls_url, '삼성전자_2018.xls')

'삼성전자_2018.xls'

In [11]:
import pandas as pd

xl = pd.ExcelFile('삼성전자_2018.xls')
xl.sheet_names

['기본정보',
 '연결 재무상태표',
 '연결 손익계산서',
 '연결 포괄손익계산서',
 '연결 자본변동표',
 '연결 현금흐름표',
 '재무상태표',
 '손익계산서',
 '포괄손익계산서',
 '자본변동표',
 '현금흐름표']

In [12]:
pd.read_excel('삼성전자_2018.xls', sheet_name='연결 손익계산서', skiprows=6)

                                       제 50 기     제 49 기     제 48 기
0                          수익(매출액)  243771415  239575376  201866745
1                             매출원가  132394411  129290661  120277715
2                            매출총이익  111377004  110284715   81589030
3                          판매비와관리비   52490335   56639677   52348358
4                         영업이익(손실)   58886669   53645038   29240672
5                             기타수익    1485037    3010657    3238261
6                             기타비용    1142018    1419648    2463814
7                            지분법이익     539845     201442      19501
8                             금융수익    9999321    9737391   11385645
9                             금융비용    8608896    8978913   10706613
10                 법인세비용차감전순이익(손실)   61159958   56195967   30713652
11                           법인세비용   16815101   14009220    7987560
12                      계속영업이익(손실)   44344857   42186747   22726092
13                       당기순이익(손실)   44344857   42186747   22726092
14                   당기순이익(손실)의 귀속
15      지배기업의 소유주에게 귀속되는 당기순이익(손실)   43890877   41344569   22415655
16           비지배지분에 귀속되는 당기순이익(손실)     453980     842178     310437
17                            주당이익
18             기본주당이익(손실) (단위 : 원)       6461       5997       3159
19             희석주당이익(손실) (단위 : 원)       6461       5997       3159