In [135]:
import os
import pandas as pd
import FinanceDataReader as fdr
from datetime import datetime

In [136]:
# 기사 데이터들 가져오기
news_path = r'../../정제데이터/기사'
news_list = [file for file in os.listdir(news_path) if 'csv' in file]
news_list

['CJ제일제당_기사_크롤링_2020.01.01_2021.12.06.csv',
 'DB손해보험_기사_크롤링_2020.01.01_2021.12.06.csv',
 'GS_기사_크롤링_2020.01.01_2021.12.06.csv',
 'GS건설_기사_크롤링_2020.01.01_2021.12.06.csv',
 'GS리테일_기사_크롤링_2020.01.01_2021.12.06.csv',
 'HMM_기사_크롤링_2020.01.01_2021.12.06.csv',
 'KB금융_기사_크롤링_2020.01.01_2021.12.06.csv',
 'KT&G_기사_크롤링_2020.01.01_2021.12.06.csv',
 'KT_기사_크롤링_2020.01.01_2021.12.06.csv',
 'LG_기사_크롤링_2020.01.01_2021.12.06.csv',
 'LG디스플레이_기사_크롤링_2020.01.01_2021.12.06.csv',
 'LG생활건강_기사_크롤링_2020.01.01_2021.12.06.csv',
 'LG유플러스_기사_크롤링_2020.01.01_2021.12.06.csv',
 'LG이노텍_기사_크롤링_2020.01.01_2021.12.06.csv',
 'LG전자_기사_크롤링_2020.01.01_2021.12.06.csv',
 'LG화학_기사_크롤링_2020.01.01_2021.12.06.csv',
 'NAVER_기사_크롤링_2020.01.01_2021.12.06.csv',
 'NH투자증권_기사_크롤링_2020.01.01_2021.12.06.csv',
 'POSCO_기사_크롤링_2020.01.01_2021.12.06.csv',
 'S-Oil_기사_크롤링_2020.01.01_2021.12.06.csv',
 'SKC_기사_크롤링_2020.01.01_2021.12.06.csv',
 'SK_기사_크롤링_2020.01.01_2021.12.06.csv',
 'SK이노베이션_기사_크롤링_2020.01.01_2021.12.06.csv',
 'SK텔레콤_기사_크롤링_2020.01.01_2021.12.06.csv',
 'SK하이닉스_기사_크롤링_2020.01.01_2021.12.06.csv',
 '강원랜드_기사_크롤링_2020.01.01_2021.12.06.csv',
 '고려아연_기사_크롤링_2020.01.01_2021.12.06.csv',
 '금호석유_기사_크롤링_2020.01.01_2021.12.06.csv',
 '기아_기사_크롤링_2020.01.01_2021.12.06.csv',
 '기업은행_기사_크롤링_2020.01.01_2021.12.06.csv',
 '넷마블_기사_크롤링_2020.01.01_2021.12.06.csv',
 '대한항공_기사_크롤링_2020.01.01_2021.12.06.csv',
 '두산밥캣_기사_크롤링_2020.01.01_2021.12.06.csv',
 '두산중공업_기사_크롤링_2020.01.01_2021.12.06.csv',
 '롯데지주_기사_크롤링_2020.01.01_2021.12.06.csv',
 '롯데케미칼_기사_크롤링_2020.01.01_2021.12.06.csv',
 '맥쿼리인프라_기사_크롤링_2020.01.01_2021.12.06.csv',
 '메리츠금융지주_기사_크롤링_2020.01.01_2021.12.06.csv',
 '메리츠증권_기사_크롤링_2020.01.01_2021.12.06.csv',
 '메리츠화재_기사_크롤링_2020.01.01_2021.12.06.csv',
 '미래에셋증권_기사_크롤링_2020.01.01_2021.12.06.csv',
 '삼성SDI_기사_크롤링_2020.01.01_2021.12.06.csv',
 '삼성물산_기사_크롤링_2020.01.01_2021.12.06.csv',
 '삼성바이오로직스_기사_크롤링_2020.01.01_2021.12.06.csv',
 '삼성생명_기사_크롤링_2020.01.01_2021.12.06.csv',
 '삼성에스디에스_기사_크롤링_2020.01.01_2021.12.06.csv',
 '삼성엔지니어링_기사_크롤링_2020.01.01_2021.12.06.csv',
 '삼성전기_기사_크롤링_2020.01.01_2021.12.06.csv',
 '삼성전자_기사_크롤링_2020.01.01_2021.12.06.csv',
 '삼성중공업_기사_크롤링_2020.01.01_2021.12.06.csv',
 '삼성카드_기사_크롤링_2020.01.01_2021.12.06.csv',
 '삼성화재_기사_크롤링_2020.01.01_2021.12.06.csv',
 '셀트리온_기사_크롤링_2020.01.01_2021.12.06.csv',
 '신한지주_기사_크롤링_2020.01.01_2021.12.06.csv',
 '쌍용C&E_기사_크롤링_2020.01.01_2021.12.06.csv',
 '아모레G_기사_크롤링_2020.01.01_2021.12.06.csv',
 '아모레퍼시픽_기사_크롤링_2020.01.01_2021.12.06.csv',
 '엔씨소프트_기사_크롤링_2020.01.01_2021.12.06.csv',
 '오리온_기사_크롤링_2020.01.01_2021.12.06.csv',
 '우리금융지주_기사_크롤링_2020.01.01_2021.12.06.csv',
 '유한양행_기사_크롤링_2020.01.01_2021.12.06.csv',
 '이마트_기사_크롤링_2020.01.01_2021.12.06.csv',
 '일진머티리얼즈_기사_크롤링_2020.01.01_2021.12.06.csv',
 '카카오_기사_크롤링_2020.01.01_2021.12.06.csv',
 '코웨이_기사_크롤링_2020.01.01_2021.12.06.csv',
 '포스코케미칼_기사_크롤링_2020.01.01_2021.12.06.csv',
 '하나금융지주_기사_크롤링_2020.01.01_2021.12.06.csv',
 '한국가스공사_기사_크롤링_2020.01.01_2021.12.06.csv',
 '한국금융지주_기사_크롤링_2020.01.01_2021.12.06.csv',
 '한국전력_기사_크롤링_2020.01.01_2021.12.06.csv',
 '한국조선해양_기사_크롤링_2020.01.01_2021.12.06.csv',
 '한국타이어앤테크놀로지_기사_크롤링_2020.01.01_2021.12.06.csv',
 '한미사이언스_기사_크롤링_2020.01.01_2021.12.06.csv',
 '한미약품_기사_크롤링_2020.01.01_2021.12.06.csv',
 '한솔케미칼_기사_크롤링_2020.01.01_2021.12.06.csv',
 '한온시스템_기사_크롤링_2020.01.01_2021.12.06.csv',
 '한전기술_기사_크롤링_2020.01.01_2021.12.06.csv',
 '한진칼_기사_크롤링_2020.01.01_2021.12.06.csv',
 '한화솔루션_기사_크롤링_2020.01.01_2021.12.06.csv',
 '현대건설_기사_크롤링_2020.01.01_2021.12.06.csv',
 '현대글로비스_기사_크롤링_2020.01.01_2021.12.06.csv',
 '현대모비스_기사_크롤링_2020.01.01_2021.12.06.csv',
 '현대제철_기사_크롤링_2020.01.01_2021.12.06.csv',
 '현대중공업지주_기사_크롤링_2020.01.01_2021.12.06.csv',
 '현대차_기사_크롤링_2020.01.01_2021.12.06.csv']

In [137]:
for stock_name in news_list:
    name = stock_name.split('_')[0]
    if name not in list(stock_code_df['Name']):
        print(name, '없음')

In [138]:
news = news_list[0]
# 날짜, 감성점수 찾기
df = pd.read_csv(os.path.join(base_path, news))
df['date'] = df['date'].apply(lambda date: datetime.strptime(date, "%Y-%m-%d")) # date dtype 바꾸기
df = df.rename(columns={'date':'Date'}).set_index('Date') # Date로 통일시켜주기

df_senti = df[['Senti_Score']].groupby('Date').mean()
df_senti

            Senti_Score
Date
2020-01-02     0.000000
2020-01-03    -0.050000
2020-01-06     0.166667
2020-01-07     0.000000
2020-01-08     0.100000
...                 ...
2021-11-25     0.066667
2021-11-26     0.200000
2021-11-29     0.133333
2021-12-02     0.400000
2021-12-03     0.250000

[346 rows x 1 columns]

In [139]:
# 코스피 종가 가져오기
kospi = fdr.DataReader('KS11', '2020-01-01', '2021-12-06')[['Change']]  # 코스피
kospi.rename(columns={'Change' : 'KOSPI'}, inplace=True)
kospi

             KOSPI
Date
2020-01-02 -0.0102
2020-01-03  0.0006
2020-01-06 -0.0098
2020-01-07  0.0095
2020-01-08 -0.0111
...            ...
2021-11-30 -0.0242
2021-12-01  0.0214
2021-12-02  0.0157
2021-12-03  0.0078
2021-12-06  0.0017

[478 rows x 1 columns]

In [140]:
# 종목코드 데이터프레임 가져오기
stock_code_file = r'../../../static/data/stockList.txt'
stock_code_df = pd.read_csv(stock_code_file)
stock_code_df

         Name  Symbol
0          3S  060310
1      AJ네트웍스  095570
2       AK홀딩스  006840
3      APS홀딩스  054620
4       AP시스템  265520
...       ...     ...
7104  흥국화재2우B  000547
7105    흥국화재우  000545
7106     흥아해운  003280
7107       희림  037440
7108       힘스  238490

[7109 rows x 2 columns]

In [141]:
# 종목코드 가져오기
stock = news.split('_')[0]
stock

'CJ제일제당'

In [142]:
stock_code = stock_code_df[stock_code_df['Name'] == stock]['Symbol'].iloc[0]
stock_code

'097950'

In [143]:
stock_df = fdr.DataReader(stock_code, '2020-01-01', '2021-12-06')
stock_df.rename(columns={'Change':'EachStock'}, inplace=True)
stock_df

              Open    High     Low   Close  Volume  EachStock
Date
2020-01-02  252500  253000  245000  245000   32615  -0.029703
2020-01-03  245500  248000  240500  241000   40183  -0.016327
2020-01-06  239500  240500  232000  233500   39960  -0.031120
2020-01-07  236000  236500  232500  234000   29816   0.002141
2020-01-08  230000  232500  227500  229500   36835  -0.019231
...            ...     ...     ...     ...     ...        ...
2021-11-30  369000  373500  351500  354000  101418  -0.040650
2021-12-01  356000  356000  344000  350500   62052  -0.009887
2021-12-02  345000  367000  345000  364500   44400   0.039943
2021-12-03  362000  371500  361000  363500   34753  -0.002743
2021-12-06  363500  365500  357000  362500   24355  -0.002751

[478 rows x 6 columns]

In [144]:
df_senti.index.dtype

dtype('<M8[ns]')

In [145]:
stock_dataset = pd.merge(stock_df, kospi, on='Date', how='inner')
stock_dataset = pd.merge(stock_dataset, df_senti, on='Date', how='left')
stock_dataset = stock_dataset.fillna(0)
stock_dataset

,Open,High,Low,Close,Volume,EachStock,KOSPI,Senti_Score
Date,,,,,,,,
2020-01-02,252500,253000,245000,245000,32615,-0.029703,-0.0102,0.000000
2020-01-03,245500,248000,240500,241000,40183,-0.016327,0.0006,-0.050000
2020-01-06,239500,240500,232000,233500,39960,-0.031120,-0.0098,0.166667
2020-01-07,236000,236500,232500,234000,29816,0.002141,0.0095,0.000000
2020-01-08,230000,232500,227500,229500,36835,-0.019231,-0.0111,0.100000
...,...,...,...,...,...,...,...,...
2021-11-30,369000,373500,351500,354000,101418,-0.040650,-0.0242,0.000000
2021-12-01,356000,356000,344000,350500,62052,-0.009887,0.0214,0.000000
2021-12-02,345000,367000,345000,364500,44400,0.039943,0.0157,0.400000
2021-12-03,362000,371500,361000,363500,34753,-0.002743,0.0078,0.250000
2021-12-06,363500,365500,357000,362500,24355,-0.002751,0.0017,0.000000

In [94]:
stock_dataset.to_csv(f'{stock}_dataset.csv')

# 여기부터 함수로 만들었음

In [129]:
import os
import pandas as pd
import FinanceDataReader as fdr
from datetime import datetime

In [130]:
# 기사 데이터들 가져오기
news_path = r'../../정제데이터/기사'
news_list = [file for file in os.listdir(news_path) if 'csv' in file]
news_list

['CJ제일제당_기사_크롤링_2020.01.01_2021.12.06.csv',
 'DB손해보험_기사_크롤링_2020.01.01_2021.12.06.csv',
 'GS_기사_크롤링_2020.01.01_2021.12.06.csv',
 'GS건설_기사_크롤링_2020.01.01_2021.12.06.csv',
 'GS리테일_기사_크롤링_2020.01.01_2021.12.06.csv',
 'HMM_기사_크롤링_2020.01.01_2021.12.06.csv',
 'KB금융_기사_크롤링_2020.01.01_2021.12.06.csv',
 'KT&G_기사_크롤링_2020.01.01_2021.12.06.csv',
 'KT_기사_크롤링_2020.01.01_2021.12.06.csv',
 'LG_기사_크롤링_2020.01.01_2021.12.06.csv',
 'LG디스플레이_기사_크롤링_2020.01.01_2021.12.06.csv',
 'LG생활건강_기사_크롤링_2020.01.01_2021.12.06.csv',
 'LG유플러스_기사_크롤링_2020.01.01_2021.12.06.csv',
 'LG이노텍_기사_크롤링_2020.01.01_2021.12.06.csv',
 'LG전자_기사_크롤링_2020.01.01_2021.12.06.csv',
 'LG화학_기사_크롤링_2020.01.01_2021.12.06.csv',
 'NAVER_기사_크롤링_2020.01.01_2021.12.06.csv',
 'NH투자증권_기사_크롤링_2020.01.01_2021.12.06.csv',
 'POSCO_기사_크롤링_2020.01.01_2021.12.06.csv',
 'S-Oil_기사_크롤링_2020.01.01_2021.12.06.csv',
 'SKC_기사_크롤링_2020.01.01_2021.12.06.csv',
 'SK_기사_크롤링_2020.01.01_2021.12.06.csv',
 'SK이노베이션_기사_크롤링_2020.01.01_2021.12.06.csv',
 'SK텔레콤_기사_크롤링_2020.01.01_2021.12.06.csv',
 'SK하이닉스_기사_크롤링_2020.01.01_2021.12.06.csv',
 '강원랜드_기사_크롤링_2020.01.01_2021.12.06.csv',
 '고려아연_기사_크롤링_2020.01.01_2021.12.06.csv',
 '금호석유_기사_크롤링_2020.01.01_2021.12.06.csv',
 '기아_기사_크롤링_2020.01.01_2021.12.06.csv',
 '기업은행_기사_크롤링_2020.01.01_2021.12.06.csv',
 '넷마블_기사_크롤링_2020.01.01_2021.12.06.csv',
 '대한항공_기사_크롤링_2020.01.01_2021.12.06.csv',
 '두산밥캣_기사_크롤링_2020.01.01_2021.12.06.csv',
 '두산중공업_기사_크롤링_2020.01.01_2021.12.06.csv',
 '롯데지주_기사_크롤링_2020.01.01_2021.12.06.csv',
 '롯데케미칼_기사_크롤링_2020.01.01_2021.12.06.csv',
 '맥쿼리인프라_기사_크롤링_2020.01.01_2021.12.06.csv',
 '메리츠금융지주_기사_크롤링_2020.01.01_2021.12.06.csv',
 '메리츠증권_기사_크롤링_2020.01.01_2021.12.06.csv',
 '메리츠화재_기사_크롤링_2020.01.01_2021.12.06.csv',
 '미래에셋증권_기사_크롤링_2020.01.01_2021.12.06.csv',
 '삼성SDI_기사_크롤링_2020.01.01_2021.12.06.csv',
 '삼성물산_기사_크롤링_2020.01.01_2021.12.06.csv',
 '삼성바이오로직스_기사_크롤링_2020.01.01_2021.12.06.csv',
 '삼성생명_기사_크롤링_2020.01.01_2021.12.06.csv',
 '삼성에스디에스_기사_크롤링_2020.01.01_2021.12.06.csv',
 '삼성엔지니어링_기사_크롤링_2020.01.01_2021.12.06.csv',
 '삼성전기_기사_크롤링_2020.01.01_2021.12.06.csv',
 '삼성전자_기사_크롤링_2020.01.01_2021.12.06.csv',
 '삼성중공업_기사_크롤링_2020.01.01_2021.12.06.csv',
 '삼성카드_기사_크롤링_2020.01.01_2021.12.06.csv',
 '삼성화재_기사_크롤링_2020.01.01_2021.12.06.csv',
 '셀트리온_기사_크롤링_2020.01.01_2021.12.06.csv',
 '신한지주_기사_크롤링_2020.01.01_2021.12.06.csv',
 '쌍용C&E_기사_크롤링_2020.01.01_2021.12.06.csv',
 '아모레G_기사_크롤링_2020.01.01_2021.12.06.csv',
 '아모레퍼시픽_기사_크롤링_2020.01.01_2021.12.06.csv',
 '엔씨소프트_기사_크롤링_2020.01.01_2021.12.06.csv',
 '오리온_기사_크롤링_2020.01.01_2021.12.06.csv',
 '우리금융지주_기사_크롤링_2020.01.01_2021.12.06.csv',
 '유한양행_기사_크롤링_2020.01.01_2021.12.06.csv',
 '이마트_기사_크롤링_2020.01.01_2021.12.06.csv',
 '일진머티리얼즈_기사_크롤링_2020.01.01_2021.12.06.csv',
 '카카오_기사_크롤링_2020.01.01_2021.12.06.csv',
 '코웨이_기사_크롤링_2020.01.01_2021.12.06.csv',
 '포스코케미칼_기사_크롤링_2020.01.01_2021.12.06.csv',
 '하나금융지주_기사_크롤링_2020.01.01_2021.12.06.csv',
 '한국가스공사_기사_크롤링_2020.01.01_2021.12.06.csv',
 '한국금융지주_기사_크롤링_2020.01.01_2021.12.06.csv',
 '한국전력_기사_크롤링_2020.01.01_2021.12.06.csv',
 '한국조선해양_기사_크롤링_2020.01.01_2021.12.06.csv',
 '한국타이어앤테크놀로지_기사_크롤링_2020.01.01_2021.12.06.csv',
 '한미사이언스_기사_크롤링_2020.01.01_2021.12.06.csv',
 '한미약품_기사_크롤링_2020.01.01_2021.12.06.csv',
 '한솔케미칼_기사_크롤링_2020.01.01_2021.12.06.csv',
 '한온시스템_기사_크롤링_2020.01.01_2021.12.06.csv',
 '한전기술_기사_크롤링_2020.01.01_2021.12.06.csv',
 '한진칼_기사_크롤링_2020.01.01_2021.12.06.csv',
 '한화솔루션_기사_크롤링_2020.01.01_2021.12.06.csv',
 '현대건설_기사_크롤링_2020.01.01_2021.12.06.csv',
 '현대글로비스_기사_크롤링_2020.01.01_2021.12.06.csv',
 '현대모비스_기사_크롤링_2020.01.01_2021.12.06.csv',
 '현대제철_기사_크롤링_2020.01.01_2021.12.06.csv',
 '현대중공업지주_기사_크롤링_2020.01.01_2021.12.06.csv',
 '현대차_기사_크롤링_2020.01.01_2021.12.06.csv']

In [131]:
# 종목코드 데이터프레임 가져오기
stock_code_file = r'../../../static/data/stockList.txt'
stock_code_df = pd.read_csv(stock_code_file)
stock_code_df

         Name  Symbol
0          3S  060310
1      AJ네트웍스  095570
2       AK홀딩스  006840
3      APS홀딩스  054620
4       AP시스템  265520
...       ...     ...
7104  흥국화재2우B  000547
7105    흥국화재우  000545
7106     흥아해운  003280
7107       희림  037440
7108       힘스  238490

[7109 rows x 2 columns]

In [132]:
# 코스피 종가 가져오기
# kospi = fdr.DataReader('KS11', '2020-01-01', '2021-12-06')[['Change']]  # 코스피
# kospi.rename(columns={'Change' : 'KOSPI'}, inplace=True)
kospi

             KOSPI
Date
2020-01-02 -0.0102
2020-01-03  0.0006
2020-01-06 -0.0098
2020-01-07  0.0095
2020-01-08 -0.0111
...            ...
2021-11-30 -0.0242
2021-12-01  0.0214
2021-12-02  0.0157
2021-12-03  0.0078
2021-12-06  0.0017

[478 rows x 1 columns]

In [146]:
def make_dataset(file_name):
    # 날짜, 감성점수 찾기
    df = pd.read_csv(os.path.join(base_path, news))
    df['date'] = df['date'].apply(lambda date: datetime.strptime(date, "%Y-%m-%d")) # date dtype 바꾸기
    df = df.rename(columns={'date':'Date'}).set_index('Date') # Date로 통일시켜주기

    df_senti = df[['Senti_Score']].groupby('Date').mean()
    
    # 종목코드 가져오기
    stock = news.split('_')[0] # 종목이름 뽑아내기
    stock_code = stock_code_df[stock_code_df['Name'] == stock]['Symbol'].iloc[0]

    # 종목 정보 가져오기
    stock_df = fdr.DataReader(stock_code, '2020-01-01', '2021-12-06')
    stock_df.rename(columns={'Change':'EachStock'}, inplace=True)
    
    # 정보 합치기
    stock_dataset = pd.merge(stock_df, kospi, on='Date', how='inner')
    stock_dataset = pd.merge(stock_dataset, df_senti, on='Date', how='left')
    stock_dataset = stock_dataset.fillna(0)
    stock_dataset
    
    # 데이터셋 저장
    stock_dataset.to_csv(f'{stock}_dataset.csv')

In [147]:
for news in news_list:
    print(news)
    print('시작')
    make_dataset(news)
    print('종료')

CJ제일제당_기사_크롤링_2020.01.01_2021.12.06.csv
시작
종료
DB손해보험_기사_크롤링_2020.01.01_2021.12.06.csv
시작
종료
GS_기사_크롤링_2020.01.01_2021.12.06.csv
시작
종료
GS건설_기사_크롤링_2020.01.01_2021.12.06.csv
시작
종료
GS리테일_기사_크롤링_2020.01.01_2021.12.06.csv
시작
종료
HMM_기사_크롤링_2020.01.01_2021.12.06.csv
시작
종료
KB금융_기사_크롤링_2020.01.01_2021.12.06.csv
시작
종료
KT&G_기사_크롤링_2020.01.01_2021.12.06.csv
시작
종료
KT_기사_크롤링_2020.01.01_2021.12.06.csv
시작
종료
LG_기사_크롤링_2020.01.01_2021.12.06.csv
시작
종료
LG디스플레이_기사_크롤링_2020.01.01_2021.12.06.csv
시작
종료
LG생활건강_기사_크롤링_2020.01.01_2021.12.06.csv
시작
종료
LG유플러스_기사_크롤링_2020.01.01_2021.12.06.csv
시작
종료
LG이노텍_기사_크롤링_2020.01.01_2021.12.06.csv
시작
종료
LG전자_기사_크롤링_2020.01.01_2021.12.06.csv
시작
종료
LG화학_기사_크롤링_2020.01.01_2021.12.06.csv
시작
종료
NAVER_기사_크롤링_2020.01.01_2021.12.06.csv
시작
종료
NH투자증권_기사_크롤링_2020.01.01_2021.12.06.csv
시작
종료
POSCO_기사_크롤링_2020.01.01_2021.12.06.csv
시작
종료
S-Oil_기사_크롤링_2020.01.01_2021.12.06.csv
시작
종료
SKC_기사_크롤링_2020.01.01_2021.12.06.csv
시작
종료
SK_기사_크롤링_2020.01.01_2021.12.06.csv
시작
종료
SK이노베이션_기사_크롤링_2020.01.01_2021.12.06.csv
시작
종료
SK텔레콤_기사_크롤링_2020.01.01_2021.12.06.csv
시작
종료
SK하이닉스_기사_크롤링_2020.01.01_2021.12.06.csv
시작
종료
강원랜드_기사_크롤링_2020.01.01_2021.12.06.csv
시작
종료
고려아연_기사_크롤링_2020.01.01_2021.12.06.csv
시작
종료
금호석유_기사_크롤링_2020.01.01_2021.12.06.csv
시작
종료
기아_기사_크롤링_2020.01.01_2021.12.06.csv
시작
종료
기업은행_기사_크롤링_2020.01.01_2021.12.06.csv
시작
종료
넷마블_기사_크롤링_2020.01.01_2021.12.06.csv
시작
종료
대한항공_기사_크롤링_2020.01.01_2021.12.06.csv
시작
종료
두산밥캣_기사_크롤링_2020.01.01_2021.12.06.csv
시작
종료
두산중공업_기사_크롤링_2020.01.01_2021.12.06.csv
시작
종료
롯데지주_기사_크롤링_2020.01.01_2021.12.06.csv
시작
종료
롯데케미칼_기사_크롤링_2020.01.01_2021.12.06.csv
시작
종료
맥쿼리인프라_기사_크롤링_2020.01.01_2021.12.06.csv
시작
종료
메리츠금융지주_기사_크롤링_2020.01.01_2021.12.06.csv
시작
종료
메리츠증권_기사_크롤링_2020.01.01_2021.12.06.csv
시작
종료
메리츠화재_기사_크롤링_2020.01.01_2021.12.06.csv
시작
종료
미래에셋증권_기사_크롤링_2020.01.01_2021.12.06.csv
시작
종료
삼성SDI_기사_크롤링_2020.01.01_2021.12.06.csv
시작
종료
삼성물산_기사_크롤링_2020.01.01_2021.12.06.csv
시작
종료
삼성바이오로직스_기사_크롤링_2020.01.01_2021.12.06.csv
시작
종료
삼성생명_기사_크롤링_2020.01.01_2021.12.06.csv
시작
종료
삼성에스디에스_기사_크롤링_2020.01.01_2021.12.06.csv
시작
종료
삼성엔지니어링_기사_크롤링_2020.01.01_2021.12.06.csv
시작
종료
삼성전기_기사_크롤링_2020.01.01_2021.12.06.csv
시작
종료
삼성전자_기사_크롤링_2020.01.01_2021.12.06.csv
시작
종료
삼성중공업_기사_크롤링_2020.01.01_2021.12.06.csv
시작
종료
삼성카드_기사_크롤링_2020.01.01_2021.12.06.csv
시작
종료
삼성화재_기사_크롤링_2020.01.01_2021.12.06.csv
시작
종료
셀트리온_기사_크롤링_2020.01.01_2021.12.06.csv
시작
종료
신한지주_기사_크롤링_2020.01.01_2021.12.06.csv
시작
종료
쌍용C&E_기사_크롤링_2020.01.01_2021.12.06.csv
시작
종료
아모레G_기사_크롤링_2020.01.01_2021.12.06.csv
시작
종료
아모레퍼시픽_기사_크롤링_2020.01.01_2021.12.06.csv
시작
종료
엔씨소프트_기사_크롤링_2020.01.01_2021.12.06.csv
시작
종료
오리온_기사_크롤링_2020.01.01_2021.12.06.csv
시작
종료
우리금융지주_기사_크롤링_2020.01.01_2021.12.06.csv
시작
종료
유한양행_기사_크롤링_2020.01.01_2021.12.06.csv
시작
종료
이마트_기사_크롤링_2020.01.01_2021.12.06.csv
시작
종료
일진머티리얼즈_기사_크롤링_2020.01.01_2021.12.06.csv
시작
종료
카카오_기사_크롤링_2020.01.01_2021.12.06.csv
시작
종료
코웨이_기사_크롤링_2020.01.01_2021.12.06.csv
시작
종료
포스코케미칼_기사_크롤링_2020.01.01_2021.12.06.csv
시작
종료
하나금융지주_기사_크롤링_2020.01.01_2021.12.06.csv
시작
종료
한국가스공사_기사_크롤링_2020.01.01_2021.12.06.csv
시작
종료
한국금융지주_기사_크롤링_2020.01.01_2021.12.06.csv
시작
종료
한국전력_기사_크롤링_2020.01.01_2021.12.06.csv
시작
종료
한국조선해양_기사_크롤링_2020.01.01_2021.12.06.csv
시작
종료
한국타이어앤테크놀로지_기사_크롤링_2020.01.01_2021.12.06.csv
시작
종료
한미사이언스_기사_크롤링_2020.01.01_2021.12.06.csv
시작
종료
한미약품_기사_크롤링_2020.01.01_2021.12.06.csv
시작
종료
한솔케미칼_기사_크롤링_2020.01.01_2021.12.06.csv
시작
종료
한온시스템_기사_크롤링_2020.01.01_2021.12.06.csv
시작
종료
한전기술_기사_크롤링_2020.01.01_2021.12.06.csv
시작
종료
한진칼_기사_크롤링_2020.01.01_2021.12.06.csv
시작
종료
한화솔루션_기사_크롤링_2020.01.01_2021.12.06.csv
시작
종료
현대건설_기사_크롤링_2020.01.01_2021.12.06.csv
시작
종료
현대글로비스_기사_크롤링_2020.01.01_2021.12.06.csv
시작
종료
현대모비스_기사_크롤링_2020.01.01_2021.12.06.csv
시작
종료
현대제철_기사_크롤링_2020.01.01_2021.12.06.csv
시작
종료
현대중공업지주_기사_크롤링_2020.01.01_2021.12.06.csv
시작
종료
현대차_기사_크롤링_2020.01.01_2021.12.06.csv
시작
종료